[project]
name = "academus"
version = "0.1.0"
description = "Ecossistema editorial e de gestÃ£o integrado â€” Academus."
authors = [
    { name = "Soeirotech", email = "contato@devillint.com.br" }
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "django",
    "python-decouple",
    "psycopg2-binary",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "dj-rest-auth (>=7.0.1,<8.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "mkdocs (>=1.6.1,<2.0.0)",
    "mkdocs-material (>=9.7.0,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


#TODO 
# ðŸ’¡ ExplicaÃ§Ã£o rÃ¡pida
# name â†’ nome do pacote (deve ser simples e sem espaÃ§os).
# version â†’ versÃ£o semÃ¢ntica (mantÃ©m o padrÃ£o 0.1.0 pra inÃ­cio).
# dependencies â†’ lista inicial das libs essenciais (vocÃª pode adicionar depois via poetry add).
# authors â†’ opcional, mas Ãºtil pra metadados e documentaÃ§Ã£o.